### ISSUE TITLE
Container not running

### ISSUE THREAD

**Issue by GoetzGoerisch** [barnstee/UA-CloudCommander#1]
@barnstee thank you for provding this! 

I'm not able to run the container:

``` text
[08:58:29 INF] Log file is: /app/ua.commander.logfile.txt
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'hostName')
   at System.Net.Dns.HostResolutionBeginHelper(String hostName, Boolean justReturnParsedIp, Boolean throwOnIIPAny, AsyncCallback requestCallback, Object state)
   at System.Net.Dns.BeginGetHostEntry(String hostNameOrAddress, AsyncCallback requestCallback, Object stateObject)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_0(String arg, AsyncCallback requestCallback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1](Func`4 beginMethod, Func`2 endMethod, TArg1 arg1, Object state)
   at System.Net.Dns.GetHostEntryAsync(String hostNameOrAddress)
   at uPLibrary.Networking.M2Mqtt.MqttNetworkChannel..ctor(String remoteHostName, Int32 remotePort, Boolean secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback, List`1 alpnProtocols)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Init(String brokerHostName, Int32 brokerPort, Boolean secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback, List`1 alpnProtocols)
   at uPLibrary.Networking.M2Mqtt.MqttClient..ctor(String brokerHostName, Int32 brokerPort, Boolean secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback, List`1 ALPNProtocols)
   at uPLibrary.Networking.M2Mqtt.MqttClient..ctor(String brokerHostName, Int32 brokerPort, Boolean secure, MqttSslProtocols sslProtocol, RemoteCertificateValidationCallback userCertificateValidationCallback, LocalCertificateSelectionCallback userCertificateSelectionCallback)
   at UACommander.MQTTClient.Connect() in /src/MQTTClient.cs:line 35
   at UACommander.Program.Main() in /src/Program.cs:line 58
   at UACommander.Program.<Main>()
```

Where am I missing a piece of information or variable I need to pass to the container?

**Comment by barnstee** [comment]
See here: https://github.com/barnstee/UACommander/blob/main/README.md#configuration

You need to specify your broker settings.

**Comment by GoetzGoerisch** [comment]
Thanks!

**Comment by barnstee** [comment]
Fixed.
