### ISSUE TITLE
Problem connecting to a MQTT Broker with username password authentication over port 8883

### ISSUE THREAD

**Issue by ChiaraK20** [barnstee/UA-CloudCommander#4]
Hello,

I tried to connect with the UA CloudCommander to a mosquitto Broker (version 1.6.9) and received the following error message on the Broker: 

<pre><code>1654849185: New connection from 172.17.0.2 on port 8883. 
1654849185: Client <unknown> disconnected due to protocol error.
</code></pre>

My settings in the mosquitto.conf are the following:
<pre><code>listener 1883
protocol mqtt

listener 8883
allow_anonymous false
password_file /etc/mosquitto/pw.txt
</code></pre>

The username and password defined in the pw.txt are matching the environment variables defined in the .env.local file. The password is in both files encoded.

The message I get from the UA-CloudCommander docker container:

<pre><code>
 Unhandled exception. uPLibrary.Networking.M2Mqtt.Exceptions.MqttConnectionException: Exception connecting to the broker
 ---> System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: Connection reset by peer.)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.FillHandshakeBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ProcessAuthenticationAsync(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at uPLibrary.Networking.M2Mqtt.MqttNetworkChannel.Connect()
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean cleanSession, UInt16 keepAlivePeriod)
   at Opc.Ua.Cloud.Commander.MQTTClient.Connect() in /src/MQTTClient.cs:line 56
   at Opc.Ua.Cloud.Commander.Program.Main() in /src/Program.cs:line 56
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Opc.Ua.Cloud.Commander.Program.Main()
   at Opc.Ua.Cloud.Commander.Program.<Main>()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at uPLibrary.Networking.M2Mqtt.MqttNetworkChannel.Connect()
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
   --- End of inner exception stack trace ---
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean cleanSession, UInt16 keepAlivePeriod)
   at Opc.Ua.Cloud.Commander.MQTTClient.Connect() in /src/MQTTClient.cs:line 56
   at Opc.Ua.Cloud.Commander.Program.Main() in /src/Program.cs:line 56
   at Opc.Ua.Cloud.Commander.Program.<Main>()
</code></pre>

What I figured out so far it is a problem with the 8883 port, which is defined for certificate authentication and inside the UA-CloudCommander it is used for username & password authentication. Could this be the problem here?

Does anyone else figured this issue or has a solution for that?

Many thanks in advance!

**Comment by barnstee** [comment]
Yes, this is the issue. Please configure the MQTT broker to allow username and password authentication. Port 8883 has nothing to do with it, 8883 is simply the default secure MQTT port.

**Comment by ChiaraK20** [comment]
okay thank you, the connection to the MQTT broker works now for me.

But I have one basic question (I am really new to all that stuff), when the CloudCommander is now running, how am I able to send a command to the OPC UA Server? So how should the message look like?

At the moment I am using [mqtt-spy](https://www.hivemq.com/blog/mqtt-toolbox-mqtt-spy/) for subscribing und publishing messages. When I publish the following to the command topic with mqtt-spy
<pre><code>{
    "Endpoint": "opc.tcp://myopcserver.contoso/UA/",
    "NodeId": "http://opcfoundation.org/UA/Station/;i=123"
}
</code></pre>

the UA-CloudCommander stops with the following exception:

<pre><code>
Unhandled exception. System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Opc.Ua.Cloud.Commander.MQTTClient.PublishReceived(Object sender, MqttMsgPublishEventArgs e) in /src/MQTTClient.cs:line 79
   at uPLibrary.Networking.M2Mqtt.MqttClient.OnMqttMsgPublishReceived(MqttMsgPublish publish)
   at uPLibrary.Networking.M2Mqtt.MqttClient.DispatchEventThread()
   at System.Threading.Thread.StartCallback()
</code></pre>

**Comment by barnstee** [comment]
You need to send the command to the following topic as described here:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#respond-to-a-direct-method

The response to the command will be sent to The MQTT topic also described there.

**Comment by barnstee** [comment]
Closing due to in inactivity. Please reopen if you are still facing issues.
